[package]
name = "axnet"
version.workspace = true
edition.workspace = true
authors = [
  "Yuekai Jia <equation618@gmail.com>",
  "ChengXiang Qi <kuangjux@outlook.com>",
]
description = "ArceOS network module"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axnet"
documentation = "https://arceos-org.github.io/arceos/axnet/index.html"

[features]
smoltcp = []
vsock = ["axdriver/vsock"]
default = ["smoltcp"]

[dependencies]
axconfig = { workspace = true }
axdriver = { workspace = true, features = ["net"] }
axhal = { workspace = true }
axsync = { workspace = true }
axtask = { workspace = true }

axerrno = { workspace = true }
axfs-ng = { workspace = true }
axfs-ng-vfs = { workspace = true }
axio = { workspace = true }
axpoll = { workspace = true }
bitflags = "2.9.1"
cfg-if = { workspace = true }
enum_dispatch = { workspace = true }
hashbrown = { workspace = true }
lazyinit = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
spin = { workspace = true }
ringbuf = { version = "0.4.8", default-features = false, features = ["alloc"] }
async-channel = { version = "2.5.0", default-features = false }
event-listener = { version = "5.4.0", default-features = false }
async-trait = "0.1.88"

[dependencies.smoltcp]
git = "https://github.com/Starry-OS/smoltcp.git"
rev = "7401a54"
default-features = false
features = [
  "alloc",
  "log",             # no std
  "async",
  "medium-ethernet",
  "medium-ip",
  "proto-ipv4",
  "proto-ipv6",
  "socket-raw",
  "socket-icmp",
  "socket-udp",
  "socket-tcp",
  "socket-dns",
  # "fragmentation-buffer-size-65536", "proto-ipv4-fragmentation",
  # "reassembly-buffer-size-65536", "reassembly-buffer-count-32",
  # "assembler-max-segment-count-32",
]
