[package]
name = "axsync"
version.workspace = true
edition.workspace = true
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "ArceOS synchronization primitives"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axsync"
documentation = "https://arceos-org.github.io/arceos/axsync/index.html"

[features]
multitask = ["axtask/multitask"]
default = []

[dependencies]
axtask.workspace = true
event-listener.workspace = true
kspin.workspace = true
lock_api.workspace = true

[dev-dependencies]
axsync = { workspace = true, features = ["multitask"] }
axtask = { workspace = true, features = ["test"] }
rand.workspace = true
