[package]
name = "axmm"
version.workspace = true
edition.workspace = true
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "ArceOS virtual memory management module"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axmm"
documentation = "https://arceos-org.github.io/arceos/axmm/index.html"

[features]
copy = ["page_table_multiarch/copy-from"]

[dependencies]
axalloc.workspace = true
axconfig.workspace = true
axerrno.workspace = true
axhal = { workspace = true, features = ["paging"] }
axsync.workspace = true
enum_dispatch.workspace = true
kspin.workspace = true
lazyinit.workspace = true
log.workspace = true
memory_addr.workspace = true
memory_set.workspace = true
page_table_multiarch = { workspace = true, optional = true }
